# Generated by Django 4.0.3 on 2022-03-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_rename_view_question_views"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="user_id",
            new_name="user",
        ),
    ]
